@host = localhost
@token = 1|Nt9jesmd6FVCVJGir45Y2hta48poZ5ObHSUFfjOR

### CSRF Cookie
GET http://{{ host }}/sanctum/csrf-cookie

### Token
POST http://{{ host }}/api/sanctum/token
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "password",
  "device_name": "insomnia"
}

### User
GET http://{{ host }}/api/users/auth
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### Roles
GET http://{{ host }}/api/roles/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### Permissions
GET http://{{ host }}/api/permissions
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}
