export { default as HomeIcon } from './HomeIcon.vue'
export { default as AvatarIcon } from './AvatarIcon.vue'
export { default as LogoutIcon } from './LogoutIcon.vue'
export { default as LoginIcon } from './LoginIcon.vue'
export { default as MailIcon } from './MailIcon.vue'
export { default as LogoIcon } from './LogoIcon.vue'
