export { default as HomeIcon } from './HomeIcon'
export { default as AvatarIcon } from './AvatarIcon'
export { default as LogoutIcon } from './LogoutIcon'
export { default as LoginIcon } from './LoginIcon'
export { default as MailIcon } from './MailIcon'
export { default as LogoIcon } from './LogoIcon'
export { default as InfoIcon } from './InfoIcon'
